### ISSUE TITLE
Crashes with textgenrnn error (issue #89 in textgenrnn)

### ISSUE THREAD

**Issue by hemangkaul** [minimaxir/tweet-generator#5]
Hi,
I'm getting the same keras output layer error that someone was getting using the textgenrnn:

`ValueError: Input tensors to a Model must come from `keras.layers.Input`. Received: Tensor("strided_slice:0", shape=(40,), dtype=float32) (missing previous layer metadata).`

The model is still being created, but when generating samples, it sometimes comes up with nonsense words. I thought I'd troubleshoot a little, and found when running interactive mode the generator was running one letter at a time:

`>>> textgen.generate(interactive=True, top_n=5)
Controls:
	s: stop.	x: backspace.	o: write your own.

Options:
	1: T
	2: I
	3: Y
	4: A
	5: W

Progress: 

Your choice?
> 2
Controls:
	s: stop.	x: backspace.	o: write your own.

Options:
	1:  
	2: t
	3: ’
	4: f
	5: n`

Any reason why this might be happening?

**Comment by hemangkaul** [comment]
https://github.com/minimaxir/textgenrnn/issues/89

**Comment by hemangkaul** [comment]
Just realized there was a config called word_level set to False. Trying that with True and seeing if it changes things.

**Comment by hemangkaul** [comment]
Yup. that was it.

**Comment by zpitroda** [comment]
didn't fix it for me :/

**Comment by timswyzen** [comment]
Getting this as well, setting word_level to True didn't help

Temporarily fixed by not setting any context_labels
